#Generated by Fabric Compiler ( version 2022.2-SP1-Lite <build 132640> ) at Sun Apr 28 12:24:53 2024

add_design "C:/Users/smn90/repo/FPGA_atoms/pango/fifo_test/source/fifo_test.v"
add_simulation "C:/Users/smn90/repo/FPGA_atoms/pango/fifo_test/source/test_fifo_test.v"
add_design C:/Users/smn90/repo/FPGA_atoms/pango/fifo_test/ipcore/fifo_t/fifo_t.idf
